Implement building resource pack

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -88,6 +88,41 @@ jobs:
         path: ${{ steps.get_filename.outputs.filename }}
         if-no-files-found: error
 
+  build-resource-pack:
+    runs-on: ubuntu-latest
+
+    needs: [info]
+
+    outputs:
+      filename: ${{ steps.get_filename.outputs.filename }}
+
+    steps:
+      - uses: actions/checkout@v2
+
+      - name: Get filename
+        id: get_filename
+        run: echo "filename=${{ needs.info.outputs.server_name }}-${{ needs.info.outputs.server_version }}-resourcepack.zip" >> $GITHUB_OUTPUT
+
+      - uses: actions/setup-python@v5
+        with:
+          python-version: '3.12'
+
+      - name: Install build requirements
+        run: |
+          python3 -m pip install --upgrade pip
+          python3 -m pip install -r requirements.txt
+
+      - name: Build resource pack
+        run: |
+          make pack
+          mv server/pack.zip ${{ steps.get_filename.outputs.filename }}
+
+      - uses: actions/upload-artifact@v4
+        with:
+          name: ${{ steps.get_filename.outputs.filename }}
+          path: ${{ steps.get_filename.outputs.filename }}
+          if-no-files-found: error
+
   info:
     runs-on: ubuntu-latest
 
@@ -131,7 +166,7 @@ jobs:
   publish-release:
     runs-on: ubuntu-latest
 
-    needs: [info, packwiz-export, mrpack-export]
+    needs: [info, packwiz-export, mrpack-export, build-resource-pack]
     if: ${{ needs.info.outputs.make_release == 'true' }}
 
     steps:
@@ -152,6 +187,10 @@ jobs:
             echo '::error::No value found for artifact `${{ needs.mrpack-export.outputs.filename }}`.' && exit 1
           fi
 
+          if [ ! -f ${{ needs.build-resource-pack.outputs.filename }} ]; then
+            echo '::error::No value found for artifact `${{ needs.build-resource-pack.outputs.filename }}`.' && exit 1
+          fi
+
       - name: Publish release
         id: release
         uses: softprops/action-gh-release@v2.3.2
@@ -162,6 +201,7 @@ jobs:
           files: |
             ${{ needs.mrpack-export.outputs.filename }}
             ${{ needs.packwiz-export.outputs.filename }}
+            ${{ needs.build-resource-pack.outputs.filename }}
           prerelease: false
           generate_release_notes: true
           token: ${{ secrets.GITHUB_TOKEN }}
