Update lint workflow for pakku

diff --git a/.github/workflows/lint.yml b/.github/workflows/lint.yml
--- a/.github/workflows/lint.yml
+++ b/.github/workflows/lint.yml
@@ -19,12 +19,28 @@ jobs:
 
     runs-on: ubuntu-latest
 
+    outputs:
+      mc_version: ${{ steps.mc_version.outputs.value }}
+
     steps:
       - name: Checkout repository
         uses: actions/checkout@v4
 
       - name: json-yaml-validate
         uses: GrantBirki/json-yaml-validate@v3.3.2
+
+      - name: Get pakku.json
+        id: pakku
+        run: echo "value=${cat pakku.json}" >> $GITHUB_OUTPUT
+
+      - name: Get server Minecraft version
+        id: mc_version
+        run: |
+          if [ ! test -f "pakku.json" ]; then
+            echo "Could not find 'pakku.json'" && exit 1
+          else
+            echo "value=${{ fromJson(steps.pakku.outputs.value).name }}"" >> $GITHUB_OUTPUT
+          fi
 
   validate-datapack:
     name: Validate Minecraft datapack 'Modally Stranded'
@@ -36,17 +52,10 @@ jobs:
     steps:
       - uses: actions/checkout@v2
 
-      - name: Get server Minecraft version
-        uses: SebRollen/toml-action@v1.2.0
-        id: mc_version
-        with:
-          file: 'server.toml'
-          field: 'mc_version'
-
       - uses: mcbeet/check-commands@v1
         with:
           source: datapacks/modally_stranded
-          minecraft: "${{ steps.mc_version.value }}"
+          minecraft: "${{ needs.validate.outputs.mc_version }}"
 
   lint-yaml:
     name: Lint YAML
